### ISSUE TITLE
valid identifier or not in c

### ISSUE THREAD

**Issue by gauravag091** [Kapoor-0905/TLE-HackSquad#67]
want to create a program in c that takes some string input and detects whether the input string is an valid identifier or not.

**Comment by kunal0411** [comment]
Hey , I would like to contribute . Can you assign me this issue? This is my first contribution.

**Comment by imrish4** [comment]
pls assign me this code

**Comment by Kapoor-0905** [comment]
Note: This repository is now not the part of Hacktoberfest 2022 
If you want to contribute as in open source then you can continue
